### ISSUE TITLE
Dead patreon link

### ISSUE THREAD

**Issue by hafidbuilds** [vkarpov15/thecodebarbarian.com#21]
Hi, your patreon link in [this](https://github.com/vkarpov15/thecodebarbarian.com/blob/master/lib/posts/20180105_express_patreon.md) post is dead. I would love to read the full article

**Comment by vkarpov15** [comment]
I can send you article via email. This is a good idea though, I may throw this article up as an ebook or something similar

**Comment by hafidbuilds** [comment]
good idea, here's my email hey.hafidz@gmail.com, thanks
