### ISSUE TITLE
Typo in https://thecodebarbarian.com/formatting-javascript-dates-with-moment-js.html

### ISSUE THREAD

**Issue by MaxGamer637** [vkarpov15/thecodebarbarian.com#51]
![Screenshot_20211225-222414-986](https://user-images.githubusercontent.com/79852483/147396538-80909d4b-fc33-4ebc-9536-6525a0742744.png)

I found a typo in the post about the moment.js (https://thecodebarbarian.com/formatting-javascript-dates-with-moment-js.html), instead of "Juni", it should be "June".

**Comment by vkarpov15** [comment]
No, that example is actually correct. Because that example shows explicitly setting the locale to "de" (Germany), and "Juni" is "June" in German

![image](https://user-images.githubusercontent.com/1620265/150651004-a677f60a-2c6c-45ca-a6b1-6793afb81a72.png)
